-- Named product identities and user-confirmed packaging. No physical stock is seeded.
-- Generic legacy IDs are archived for historical references; they are never active choices.
insert into public.products(id,definition) values
('tap','{"family":"Norrlands","flavour":"Export","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"keg","sizeMl":30000,"_version":1,"brand":"Norrlands Guld","productType":"Beer","name":"Norrlands Guld Export · 30 L keg","supplier":"Spendrups","requestFactor":50,"id":"tap","group":"Beer","unit":"glasses","pack":50,"rate":75,"minimum":25,"capacity":350,"requestUnit":"30 L kegs","note":"50 usable glasses per keg · 7 keg slots","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('beer50','{"family":"Mariestad","flavour":"Export","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":500,"_version":1,"brand":"Mariestad","productType":"Beer","name":"Mariestad Export · 50 cl bottle","supplier":"Spendrups","requestFactor":1,"id":"beer50","group":"Beer","unit":"bottles","pack":15,"rate":12.8,"minimum":5,"tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('beer33','{"family":"Beer · 33 cl","flavour":"","location":"Storage","shelf":0,"archived":true,"kind":"occasional","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"supplier":"Spendrups","requestFactor":1,"id":"beer33","name":"Beer · 33 cl","group":"Beer & cider","unit":"bottles","pack":24,"rate":5.4,"minimum":5,"tagSchemaVersion":2,"brand":"","productType":"Beer & cider","tags":[],"unverifiedIdentity":true,"packAssumed":false}'::jsonb),
('guinness','{"family":"Guinness · 44 cl","flavour":"Stout","location":"Storage","shelf":0,"archived":false,"kind":"occasional","reorder":true,"countMode":"pack","sizeMl":440,"_version":1,"brand":"Guinness","productType":"Beer","packAssumed":true,"supplier":"Martin & Servera","requestFactor":1,"id":"guinness","name":"Guinness · 44 cl","group":"Beer","unit":"cans","pack":24,"rate":21.7,"minimum":8,"tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false}'::jsonb),
('cider','{"family":"Cider · 33 cl","flavour":"","location":"Storage","shelf":0,"archived":true,"kind":"occasional","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"supplier":"Spendrups","requestFactor":1,"id":"cider","name":"Cider · 33 cl","group":"Beer & cider","unit":"bottles","pack":24,"rate":34.2,"minimum":12,"tagSchemaVersion":2,"brand":"","productType":"Beer & cider","tags":[],"unverifiedIdentity":true,"packAssumed":false}'::jsonb),
('smirnoff','{"family":"Smirnoff Ice","flavour":"Ice","location":"Storage","shelf":0,"archived":false,"kind":"occasional","reorder":true,"countMode":"pack","sizeMl":275,"_version":1,"brand":"Smirnoff","productType":"RTD","name":"Smirnoff Ice · 27.5 cl bottle","supplier":"Spendrups","requestFactor":1,"id":"smirnoff","group":"RTD","unit":"bottles","pack":24,"rate":7.3,"minimum":5,"tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('alcoholfree','{"family":"Alcohol-free beer / cider","flavour":"","location":"Storage","shelf":0,"archived":true,"kind":"occasional","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"supplier":"Spendrups","requestFactor":1,"id":"alcoholfree","name":"Alcohol-free beer / cider","group":"Alcohol-free","unit":"bottles","pack":24,"rate":2,"minimum":4,"packAssumed":true,"tagSchemaVersion":2,"brand":"","productType":"Alcohol-free","tags":[],"unverifiedIdentity":true}'::jsonb),
('cola','{"family":"Coca-Cola","flavour":"Original","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"brand":"Coca-Cola","productType":"Soft drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"cola","name":"Coca-Cola","group":"Soft drink","unit":"cans","pack":20,"rate":5,"minimum":5,"capacity":40,"note":"Variant split is a planning assumption","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('colazero','{"family":"Coca-Cola Zero","flavour":"Zero","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"brand":"Coca-Cola","productType":"Soft drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"colazero","name":"Coca-Cola Zero","group":"Soft drink","unit":"cans","pack":20,"rate":4,"minimum":5,"capacity":40,"note":"Variant split is a planning assumption","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('fanta','{"family":"Fanta","flavour":"Original","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"brand":"Fanta","productType":"Soft drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"fanta","name":"Fanta","group":"Soft drink","unit":"cans","pack":20,"rate":3,"minimum":5,"capacity":40,"note":"Variant split is a planning assumption","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('fantazero','{"family":"Fanta Zero","flavour":"Zero","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"brand":"Fanta","productType":"Soft drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"fantazero","name":"Fanta Zero","group":"Soft drink","unit":"cans","pack":20,"rate":2,"minimum":5,"capacity":40,"note":"Variant split is a planning assumption","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('sprite','{"family":"Sprite","flavour":"Original","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"brand":"Sprite","productType":"Soft drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"sprite","name":"Sprite","group":"Soft drink","unit":"cans","pack":20,"rate":4,"minimum":5,"capacity":40,"note":"Variant split is a planning assumption","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('spritezero','{"family":"Sprite Zero","flavour":"Zero","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":330,"_version":1,"brand":"Sprite","productType":"Soft drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"spritezero","name":"Sprite Zero","group":"Soft drink","unit":"cans","pack":20,"rate":3,"minimum":5,"capacity":40,"note":"Variant split is a planning assumption","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('redbull','{"family":"Red Bull","flavour":"Original","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":250,"_version":1,"brand":"Red Bull","productType":"Energy drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"redbull","name":"Red Bull","group":"Energy drink","unit":"cans","pack":24,"rate":4,"minimum":4,"capacity":24,"note":"Includes estimated mixer use","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('redbullzero','{"family":"Red Bull","flavour":"Sugarfree","location":"Storage","shelf":0,"archived":false,"kind":"staple","reorder":true,"countMode":"pack","sizeMl":250,"_version":1,"brand":"Red Bull","productType":"Energy drink","alcoholFree":true,"supplier":"Spendrups","requestFactor":1,"id":"redbullzero","name":"Red Bull Sugarfree","group":"Energy drink","unit":"cans","pack":24,"rate":3,"minimum":4,"capacity":24,"note":"Includes estimated mixer use","tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('pet','{"family":"Soft drinks · 50 cl PET","flavour":"","location":"Storage","shelf":0,"archived":true,"kind":"occasional","reorder":true,"countMode":"pack","sizeMl":500,"_version":1,"supplier":"Spendrups","requestFactor":1,"id":"pet","name":"Soft drinks · 50 cl PET","group":"Soft drinks","unit":"bottles","pack":24,"rate":6,"minimum":4,"note":"24 per Spendrups crate; M&S packs vary","tagSchemaVersion":2,"brand":"","productType":"Soft drinks","tags":[],"unverifiedIdentity":true,"packAssumed":false}'::jsonb),
('briska-mango-can','{"family":"Briska Mango · 33 cl can","flavour":"Mango","location":"Storage","shelf":0,"archived":false,"kind":"seasonal","reorder":false,"countMode":"pack","sizeMl":330,"_version":1,"supplier":"Spendrups","requestFactor":1,"id":"briska-mango-can","name":"Briska Mango · 33 cl can","brand":"Briska","productType":"Cider","group":"Cider","unit":"cans","pack":24,"rate":0,"minimum":0,"tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('briska-demi-sec-glass','{"family":"Briska Demi Sec · 33 cl glass","flavour":"Demi Sec","location":"Storage","shelf":0,"archived":false,"kind":"seasonal","reorder":false,"countMode":"pack","sizeMl":330,"_version":1,"supplier":"Spendrups","requestFactor":1,"id":"briska-demi-sec-glass","name":"Briska Demi Sec · 33 cl glass","brand":"Briska","productType":"Cider","group":"Cider","unit":"bottles","pack":24,"rate":0,"minimum":0,"tagSchemaVersion":2,"tags":[],"unverifiedIdentity":false,"packAssumed":false}'::jsonb),
('sparkling','{"family":"Sparkling wine","flavour":"","location":"Storage","shelf":0,"archived":true,"kind":"occasional","reorder":true,"countMode":"pack","sizeMl":750,"_version":1,"supplier":"Spendrups","requestFactor":1,"id":"sparkling","name":"Sparkling wine","group":"Wine","unit":"bottles","pack":1,"rate":0,"minimum":0,"note":"Event orders only; pack size needs confirmation","tagSchemaVersion":2,"brand":"","productType":"Wine","tags":[],"unverifiedIdentity":true,"packAssumed":false}'::jsonb)
on conflict(id) do nothing;
