import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {productLibrary} from '../site/library.js';
test('library opens with categories and only reveals matching products',()=>{
 const products=[{id:'cola',name:'Cola',group:'Soda',pack:20,unit:'cans',location:'Storage'},{id:'gin',name:'Gin',group:'Spirits',countMode:'bottle',sizeMl:700,location:'Bar'}];
 assert.ok(!productLibrary(products).includes('data-id="cola"'));
 assert.ok(productLibrary(products,{query:'cola'}).includes('data-id="cola"'));
 assert.ok(!productLibrary(products,{query:'cola'}).includes('data-id="gin"'));
 assert.ok(productLibrary(products,{category:'Spirits'}).includes('data-id="gin"'));
});
test('supplier receipts enforce privacy, snapshots, explicit checks and atomic exactly-once stock',async()=>{
 const db=new PGlite(),user='11111111-1111-4111-8111-111111111111';
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on all functions in schema auth to authenticated,anon;`);
 for(const file of ['schema.sql','catalog.sql','inventory.sql','deliveries.sql','deliveries.sql'])await db.exec(await readFile('supabase/'+file,'utf8'));
 await db.exec(`insert into auth.users values('${user}');insert into public.members values('admin@example.org','admin',true),('member@example.org','member',true);`);
 const login=async(email)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,email})]);await db.exec('set role authenticated');};
 const rpc=async(name,payload)=>(await db.query(`select public.${name}($1::jsonb) value`,[JSON.stringify(payload)])).rows[0].value;
 const order={id:crypto.randomUUID(),version:0,reference:'QP-test-1',supplier:'Spendrups',delivery_date:'2026-10-13',lines:[{product_id:'cola',full:2,loose:0},{product_id:'beer50',full:1,loose:0}]};
 await login('member@example.org');await assert.rejects(rpc('save_supplier_order',order),/Barmaster/);
 await login('admin@example.org');order.version=await rpc('save_supplier_order',order);
 assert.equal((await db.query('select count(*) n from public.stock_movements')).rows[0].n,0);
 await assert.rejects(rpc('save_supplier_order',{...order,version:0}),/another device/);
 await assert.rejects(rpc('save_supplier_order',{...order,version:null}),/another device/);
 await login('member@example.org');assert.equal((await db.query('select * from public.supplier_orders')).rows.length,0);
 await assert.rejects(rpc('receive_supplier_order',{id:order.id}),/Barmaster/);
 await login('admin@example.org');
 // Pack edits after ordering must not reinterpret the supplier's expected pack.
 await db.exec('reset role');await db.exec(`update public.products set definition=jsonb_set(definition,'{pack}','24') where id='cola'`);await login('admin@example.org');
 let receipt={id:order.id,version:order.version,received_at:new Date().toISOString(),note:'One pack missing',lines:[{product_id:'cola',full:1,loose:0,checked:true},{product_id:'beer50',full:1,loose:0,checked:false}]};
 await assert.rejects(rpc('receive_supplier_order',receipt),/Confirm each/);
 assert.equal((await db.query('select count(*) n from public.stock_movements')).rows[0].n,0);
 receipt.lines[1].checked=true;
 await assert.rejects(rpc('receive_supplier_order',{...receipt,note:''}),/note/);
 await assert.rejects(rpc('receive_supplier_order',{...receipt,lines:[receipt.lines[0],receipt.lines[0]]}),/Duplicate/);
 await assert.rejects(rpc('receive_supplier_order',{...receipt,version:0}),/Order changed/);
 await rpc('receive_supplier_order',receipt);await rpc('receive_supplier_order',receipt);
 const moves=(await db.query('select product_id,quantity from public.stock_movements order by product_id')).rows;
 assert.deepEqual(moves,[{product_id:'beer50',quantity:'15'},{product_id:'cola',quantity:'20'}]);
 const saved=(await db.query('select * from public.supplier_orders where id=$1',[order.id])).rows[0];
 assert.equal(saved.receipt.lines[0].difference,-20);assert.equal(saved.status,'received');
 await assert.rejects(rpc('save_supplier_order',order),/already received/);
 const kegOrder={...order,id:crypto.randomUUID(),version:0,reference:'QP-kegs',lines:[{product_id:'tap',full:2,loose:0}]};kegOrder.version=await rpc('save_supplier_order',kegOrder);
 await rpc('receive_supplier_order',{id:kegOrder.id,version:kegOrder.version,received_at:new Date().toISOString(),note:'',lines:[{product_id:'tap',full:2,loose:0,checked:true}]});
 assert.equal((await db.query("select count(*) n from public.keg_slots where state='warm'")).rows[0].n,2);
 const excessive={...kegOrder,id:crypto.randomUUID(),version:0,reference:'QP-too-many'};excessive.version=await rpc('save_supplier_order',excessive);
 await assert.rejects(rpc('receive_supplier_order',{id:excessive.id,version:excessive.version,received_at:new Date().toISOString(),note:'Extra kegs',lines:[{product_id:'tap',full:6,loose:0,checked:true}]}),/empty keg slots/);
 assert.equal((await db.query('select status from public.supplier_orders where id=$1',[excessive.id])).rows[0].status,'ordered');
 const missing={...order,id:crypto.randomUUID(),version:0,reference:'QP-missing',lines:[{product_id:'beer50',full:1,loose:0}]};missing.version=await rpc('save_supplier_order',missing);
 const zero={id:missing.id,version:missing.version,received_at:new Date().toISOString(),note:'Nothing arrived',lines:[{product_id:'beer50',full:0,loose:0,checked:true}]};
 await rpc('receive_supplier_order',zero);await rpc('receive_supplier_order',zero);
 assert.equal((await db.query('select count(*) n from public.stock_movements where batch_id=$1',[missing.id])).rows[0].n,0);
 const unplanned={...order,id:crypto.randomUUID(),version:0,reference:'QP-unplanned',unplanned:true,lines:[{product_id:'beer50',full:1,loose:0}]};unplanned.version=await rpc('save_supplier_order',unplanned);
 await rpc('receive_supplier_order',{id:unplanned.id,version:unplanned.version,received_at:new Date().toISOString(),note:'',lines:[{product_id:'beer50',full:1,loose:0,checked:true}]});
 const unplannedReceipt=(await db.query('select receipt from public.supplier_orders where id=$1',[unplanned.id])).rows[0].receipt;
 assert.equal(unplannedReceipt.lines[0].quantity,null);assert.equal(unplannedReceipt.lines[0].difference,null);assert.equal(unplannedReceipt.lines[0].received,15);
 await db.close();
});
