"""Focused phone flows, using fictional products and an ephemeral local preview."""
from pathlib import Path
from datetime import datetime,timedelta
from zoneinfo import ZoneInfo
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1]
(ROOT/'test-results').mkdir(exist_ok=True)
with sync_playwright() as p:
 executable='/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None
 browser=p.chromium.launch(executable_path=executable,headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':390,'height':844});errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 today=datetime.now(ZoneInfo('Europe/Stockholm')).date()
 def fictional_history(route):
  response=route.fetch();state=response.json();sales=[]
  for offset in range(1,30):
   date=today-timedelta(days=offset)
   if date.weekday() not in [2,4]:continue
   factor=1 if date.weekday()==2 else 2
   for product,quantity in [('QP - Öl på tapp 50 cl',20*factor),('QP - Cider',10*factor),('QP - Märke',8)]:
    sales.append({'date':date.isoformat(),'product':product,'category':'QP','quantity':quantity,'gross_ore':quantity*3500,'source_rows':quantity})
  state['sales']=sales;state['imports']=[{'range_start':(today-timedelta(days=29)).isoformat(),'range_end':today.isoformat(),'included_rows':len(sales),'excluded_rows':0,'unclassified_rows':0,'refund_rows':0}]
  route.fulfill(response=response,json=state)
 page.route('**/__preview/state',fictional_history)
 page.goto('http://127.0.0.1:4173/',wait_until='networkidle')
 expect(page.locator('.stock-table').first).not_to_be_visible()
 page.goto('http://127.0.0.1:4173/#history',wait_until='networkidle')
 expect(page.locator('#from')).to_have_value((today-timedelta(days=29)).isoformat())
 expect(page.locator('#to')).to_have_value(today.isoformat())
 expect(page.get_by_role('heading',name='Wednesday & Friday · year view',exact=True)).to_be_visible()
 expect(page.locator('.pub-year-chart svg')).to_be_visible()
 page.locator('#pub-year-metric').select_option('drinks')
 expect(page.locator('.pub-year-averages').locator('div').nth(0)).to_contain_text('30 drink items')
 expect(page.locator('.pub-year-averages').locator('div').nth(1)).to_contain_text('60 drink items')
 page.locator('#pub-year-basis').select_option('marked')
 expect(page.locator('.pub-year .empty')).to_be_visible()
 page.locator('#pub-year-basis').select_option('observed')
 assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Year graph overflows phone viewport'
 page.screenshot(path=str(ROOT/'test-results/focused-pub-year.png'))
 expect(page.get_by_role('heading',name='Wednesday & Friday pubs',exact=True)).to_be_visible()
 page.get_by_text('Customer workload estimate',exact=True).click()
 page.locator('#pub-purchases-per-customer').fill('2')
 expect(page.locator('#pub-customer-scenario')).to_contain_text('≈15 customers')
 expect(page.locator('#pub-customer-scenario')).to_contain_text('≈30 customers')
 page.screenshot(path=str(ROOT/'test-results/focused-pub-insights.png'))
 page.get_by_role('button',name='Past 30 days',exact=True).click()
 expect(page.locator('#from')).to_have_value((today-timedelta(days=29)).isoformat())
 page.goto('http://127.0.0.1:4173/#stock',wait_until='networkidle')
 page.get_by_role('button',name='Count stock',exact=False).click()
 dialog=page.get_by_role('dialog',name='Stock editor')
 assert dialog.locator('.library-result').count()==0
 dialog.get_by_role('button',name='Add product',exact=True).click()
 dialog.get_by_label('Brand',exact=True).fill('Briska')
 dialog.get_by_label('Product type',exact=True).select_option('Cider')
 dialog.get_by_label('Flavour / variant').fill('Mango test')
 dialog.get_by_label('Container',exact=True).select_option('cans')
 dialog.get_by_label('Container size · ml',exact=True).fill('330')
 dialog.get_by_label('Units / pack',exact=True).fill('24')
 assert dialog.get_by_label('Storage location',exact=True).count()==0
 assert dialog.get_by_label('Start from',exact=True).count()==0
 dialog.get_by_role('button',name='Save product',exact=True).click()
 expect(dialog.get_by_role('heading',name='Briska Mango test',exact=True)).to_be_visible()
 expect(dialog.get_by_role('button',name='Save count',exact=True)).to_be_disabled()
 dialog.get_by_role('button',name='Increase Full packs').click()
 dialog.get_by_label('Loose units',exact=True).fill('')
 expect(dialog.get_by_role('button',name='Save count',exact=True)).to_be_disabled()
 dialog.get_by_label('Loose units',exact=True).fill('12')
 dialog.get_by_label('Loose units',exact=True).blur()
 expect(dialog.locator('.count-total')).to_have_text('36 cans')
 page.screenshot(path=str(ROOT/'test-results/focused-count.png'))
 dialog.get_by_role('button',name='Close',exact=True).click()
 page.get_by_role('button',name='Count stock',exact=False).click()
 dialog.get_by_text('1 unfinished count',exact=True).click()
 dialog.get_by_role('button',name='Continue',exact=True).click()
 expect(dialog.locator('.count-total')).to_have_text('36 cans')
 dialog.get_by_role('button',name='Save count',exact=True).click()
 expect(dialog.locator('#count-feedback')).to_contain_text('saved · 36 cans')
 expect(dialog.get_by_text('1 unfinished count',exact=True)).to_have_count(0)
 dialog.get_by_label('Find a product').fill('Mango test')
 dialog.locator('.library-result').first.click()
 expect(dialog.locator('.count-total')).to_have_text('0 cans')
 expect(dialog.get_by_role('button',name='Save count',exact=True)).to_be_disabled()
 dialog.get_by_role('button',name='Back',exact=True).click()
 dialog.get_by_role('button',name='Count history',exact=True).click()
 expect(dialog).to_contain_text('36 cans')
 dialog.get_by_role('button',name='Back to products',exact=True).click()

 # Opened spirits remain a separate, simple tally.
 dialog.get_by_role('button',name='Add product',exact=True).click()
 dialog.get_by_label('Brand',exact=True).fill('House')
 dialog.get_by_label('Product type',exact=True).select_option('Spirit')
 dialog.get_by_label('Product name (optional)',exact=True).fill('House gin 70 cl')
 dialog.get_by_role('button',name='Save product',exact=True).click()
 dialog.get_by_role('button',name='Increase Full bottles').click()
 dialog.get_by_role('button',name='+ Opened bottle',exact=True).click()
 dialog.get_by_role('button',name='¼',exact=True).click()
 expect(dialog.locator('.count-total')).to_contain_text('875 ml')
 dialog.get_by_role('button',name='Save count',exact=True).click()
 dialog.get_by_role('button',name='Manage library',exact=True).click()
 dialog.get_by_label('Find a product').fill('House gin')
 dialog.get_by_role('button',name='House gin 70 cl',exact=False).click()
 dialog.get_by_role('button',name='Archive product',exact=True).click()
 expect(dialog.locator('.library-result')).to_have_count(0)
 dialog.get_by_role('button',name='Show archived',exact=True).click()
 dialog.get_by_label('Find a product').fill('House gin')
 dialog.get_by_role('button',name='House gin 70 cl',exact=False).click()
 dialog.get_by_role('button',name='Restore product',exact=True).click()
 dialog.get_by_role('button',name='Close',exact=True).click()
 dialog.locator('#countpick-facet').select_option('brand')
 dialog.get_by_role('button',name='Briska',exact=False).first.click()
 expect(dialog.locator('.library-result')).to_have_count(3)
 dialog.get_by_text('Filter further',exact=True).click()
 dialog.locator('#countpick-facet').select_option('type')
 dialog.get_by_text('Filter further',exact=True).click()
 dialog.get_by_role('button',name='Cider',exact=True).click()
 expect(dialog.locator('.library-result')).to_have_count(3)
 dialog.get_by_label('Find a product').fill('Mango')
 expect(dialog.locator('.library-result')).to_have_count(2)
 dialog.get_by_role('button',name='Count these 2 products',exact=True).click()
 dialog.get_by_role('button',name='Increase Full packs').click()
 dialog.get_by_role('button',name='Save & next',exact=True).click()
 expect(dialog).to_contain_text('1 saved')
 dialog.get_by_role('button',name='Skip',exact=True).click()
 expect(dialog).to_contain_text('1 saved · 1 skipped')
 page.screenshot(path=str(ROOT/'test-results/focused-guided.png'))
 dialog.get_by_role('button',name='Done',exact=True).click()
 dialog.get_by_role('button',name='Close',exact=True).click()
 page.get_by_role('button',name='Record an order',exact=False).click()
 delivery=page.get_by_role('dialog',name='Deliveries')
 delivery.get_by_label('Order reference',exact=True).fill('QP-browser-test')
 delivery.get_by_label('Delivery date',exact=True).fill('2026-10-13')
 delivery.get_by_label('Find a product').fill('Coca-Cola')
 delivery.locator('.library-result').first.click()
 delivery.get_by_role('button',name='Increase Full packs').click()
 delivery.get_by_role('button',name='Increase Full packs').click()
 delivery.get_by_role('button',name='Set amount',exact=True).click()
 delivery.get_by_role('button',name='Save expected order',exact=True).click()
 delivery.get_by_role('button',name='Spendrups',exact=False).first.click()
 expect(delivery).to_contain_text('Ordered: 40 cans')
 delivery.get_by_role('button',name='Increase Full packs').click()
 delivery.get_by_role('button',name='Confirm & next',exact=True).click()
 expect(delivery).to_contain_text('20 missing')
 delivery.get_by_role('button',name='Confirm delivery',exact=True).click()
 expect(delivery.get_by_role('alert')).to_contain_text('Explain missing or extra items')
 delivery.get_by_label('Delivery note',exact=False).fill('One pack missing')
 delivery.get_by_role('button',name='Confirm delivery',exact=True).click()
 expect(delivery.get_by_role('heading',name='Delivery recorded',exact=True)).to_be_visible()
 expect(delivery).to_contain_text('20 received / 40 ordered')
 page.screenshot(path=str(ROOT/'test-results/focused-delivery.png'))
 delivery.get_by_role('button',name='Done',exact=True).click()
 page.get_by_role('button',name='Count stock',exact=False).click()
 dialog.get_by_role('button',name='Kegs & tap gas',exact=True).click()
 tap=page.get_by_role('dialog',name='Tap room')
 tap.locator('[data-slot="4"]').click()
 tap.get_by_role('button',name='½',exact=True).click()
 expect(tap.locator('#tap-yield')).to_have_text('≈25 expected servings')
 tap.get_by_role('button',name='Back to all kegs',exact=True).click()
 tap.get_by_role('button',name='Save keg count',exact=True).click()
 expect(tap).not_to_be_visible()
 page.get_by_role('button',name='Count stock',exact=False).click()
 dialog.get_by_role('button',name='Kegs & tap gas',exact=True).click()
 tap=page.get_by_role('dialog',name='Tap room')
 tap.get_by_text('Tap gas · internal supply',exact=True).click()
 expect(tap.locator('#gas-reserve')).to_have_text('Not counted yet.')
 tap.locator('[name="full"]').fill('1')
 tap.locator('[name="in_use"]').fill('1')
 tap.locator('[name="empty"]').fill('2')
 tap.get_by_role('button',name='Save gas count',exact=True).click()
 expect(tap).not_to_be_visible()
 page.get_by_role('button',name='Count stock',exact=False).click()
 dialog.get_by_role('button',name='Kegs & tap gas',exact=True).click()
 tap=page.get_by_role('dialog',name='Tap room')
 tap.get_by_text('Tap gas · internal supply',exact=True).click()
 expect(tap.locator('[name="full"]')).to_have_value('1')
 page.screenshot(path=str(ROOT/'test-results/focused-tap.png'))
 tap.get_by_role('button',name='Close tap room',exact=True).click()
 for width in [320,360,390,430,768]:
  page.set_viewport_size({'width':width,'height':844})
  for route in ['stock','history','requests']:
   page.goto('http://127.0.0.1:4173/#'+route,wait_until='networkidle')
   assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),(width,route)
  page.goto('http://127.0.0.1:4173/',wait_until='networkidle')
  page.get_by_role('button',name='Count stock',exact=False).click()
  dialog.get_by_label('Find a product').fill('cola')
  assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),(width,'library')
  dialog.locator('.library-result').first.click()
  assert dialog.evaluate('(d)=>d.scrollWidth<=d.clientWidth+1'),(width,'counter')
  dialog.get_by_role('button',name='Back',exact=True).click()
  dialog.get_by_role('button',name='Kegs & tap gas',exact=True).click()
  tap=page.get_by_role('dialog',name='Tap room')
  tap.locator('[data-slot="1"]').click()
  assert tap.evaluate('(d)=>d.scrollWidth<=d.clientWidth+1'),(width,'tap')
  tap.get_by_role('button',name='Close tap room',exact=True).click()
 assert not errors,errors
 browser.close()
print('Focused product selection, templates, count resume, spirits, archives, receiving and mobile widths passed.')
