"""Focused phone flows, using fictional products and an ephemeral local preview."""
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1]
(ROOT/'test-results').mkdir(exist_ok=True)
with sync_playwright() as p:
 executable='/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None
 browser=p.chromium.launch(executable_path=executable,headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':390,'height':844});errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:4173/',wait_until='networkidle')
 expect(page.locator('.stock-table').first).not_to_be_visible()
 page.get_by_role('button',name='Count stock',exact=False).click()
 dialog=page.get_by_role('dialog',name='Stock editor')
 assert dialog.locator('.library-result').count()==0
 dialog.get_by_role('button',name='Add product',exact=True).click()
 dialog.get_by_label('Start from').select_option('briskaCan')
 expect(dialog.get_by_label('Start from')).to_have_value('briskaCan')
 dialog.get_by_label('Product name',exact=True).fill('Briska Mango test')
 dialog.get_by_label('Flavour / brand').fill('Mango')
 dialog.get_by_label('Storage location',exact=True).fill('Test shelf')
 expect(dialog.get_by_label('Units per pack / crate')).to_have_value('24')
 dialog.get_by_role('button',name='Save product',exact=True).click()
 dialog.get_by_role('button',name='Briska Mango test',exact=False).click()
 dialog.get_by_role('button',name='Continue count',exact=True).click()
 expect(dialog.locator('.eyebrow').last).to_contain_text('1 / 1')
 dialog.get_by_role('button',name='Increase Full packs').click()
 dialog.get_by_label('Loose units',exact=True).fill('12')
 dialog.get_by_label('Loose units',exact=True).blur()
 expect(dialog.locator('.count-total')).to_have_text('36 cans')
 page.screenshot(path=str(ROOT/'test-results/focused-count.png'))
 dialog.get_by_role('button',name='Close',exact=True).click()
 page.get_by_role('button',name='Count stock',exact=False).click()
 dialog.get_by_role('button',name='Continue count',exact=True).click()
 expect(dialog.locator('.count-total')).to_have_text('36 cans')
 dialog.get_by_role('button',name='Confirm & next',exact=True).click()
 dialog.get_by_role('button',name='Publish count',exact=True).click()
 expect(dialog.locator('#draft-status')).to_have_text('Preview count applied')
 # Opened spirits remain a separate, simple tally.
 dialog.get_by_role('button',name='Add product',exact=True).click()
 dialog.get_by_label('Start from').select_option('spirit')
 dialog.get_by_label('Product name',exact=True).fill('House gin 70 cl')
 dialog.get_by_role('button',name='Save product',exact=True).click()
 dialog.get_by_role('button',name='House gin 70 cl',exact=False).click()
 dialog.get_by_role('button',name='Continue count',exact=True).click()
 dialog.get_by_role('button',name='Increase Full bottles').click()
 dialog.get_by_role('button',name='+ Opened bottle',exact=True).click()
 dialog.get_by_role('button',name='¼',exact=True).click()
 expect(dialog.locator('.count-total')).to_contain_text('875 ml')
 dialog.get_by_role('button',name='Confirm & next',exact=True).click()
 dialog.get_by_role('button',name='Publish count',exact=True).click()
 dialog.get_by_role('button',name='Manage library',exact=True).click()
 dialog.get_by_label('Find a product').fill('House gin')
 dialog.get_by_role('button',name='House gin 70 cl',exact=False).click()
 dialog.get_by_role('button',name='Archive product',exact=True).click()
 expect(dialog.locator('.library-result')).to_have_count(0)
 dialog.get_by_role('button',name='Manage library',exact=True).click()
 dialog.get_by_role('button',name='Show archived',exact=True).click()
 dialog.get_by_label('Find a product').fill('House gin')
 dialog.get_by_role('button',name='House gin 70 cl',exact=False).click()
 dialog.get_by_role('button',name='Restore product',exact=True).click()
 dialog.get_by_role('button',name='Close',exact=True).click()
 page.get_by_role('button',name='Record an order',exact=False).click()
 delivery=page.get_by_role('dialog',name='Deliveries')
 delivery.get_by_label('Order reference',exact=True).fill('QP-browser-test')
 delivery.get_by_label('Delivery date',exact=True).fill('2026-10-13')
 delivery.get_by_label('Find a product').fill('Coca-Cola')
 delivery.locator('.library-result').first.click()
 delivery.get_by_role('button',name='Increase Full packs').click()
 delivery.get_by_role('button',name='Increase Full packs').click()
 delivery.get_by_role('button',name='Set amount',exact=True).click()
 delivery.get_by_role('button',name='Save expected order',exact=True).click()
 delivery.get_by_role('button',name='Spendrups',exact=False).first.click()
 expect(delivery).to_contain_text('Ordered: 40 cans')
 delivery.get_by_role('button',name='Increase Full packs').click()
 delivery.get_by_role('button',name='Confirm & next',exact=True).click()
 expect(delivery).to_contain_text('20 missing')
 delivery.get_by_role('button',name='Confirm delivery',exact=True).click()
 expect(delivery.get_by_role('alert')).to_contain_text('Explain missing or extra items')
 delivery.get_by_label('Delivery note',exact=False).fill('One pack missing')
 delivery.get_by_role('button',name='Confirm delivery',exact=True).click()
 expect(delivery.get_by_role('heading',name='Delivery recorded',exact=True)).to_be_visible()
 expect(delivery).to_contain_text('20 received / 40 ordered')
 page.screenshot(path=str(ROOT/'test-results/focused-delivery.png'))
 delivery.get_by_role('button',name='Done',exact=True).click()
 for width in [320,360,390,430,768]:
  page.set_viewport_size({'width':width,'height':844})
  for route in ['stock','history','requests']:
   page.goto('http://127.0.0.1:4173/#'+route,wait_until='networkidle')
   assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),(width,route)
  page.goto('http://127.0.0.1:4173/',wait_until='networkidle')
  page.get_by_role('button',name='Count stock',exact=False).click()
  dialog.get_by_label('Find a product').fill('cola')
  assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),(width,'library')
  dialog.get_by_role('button',name='Close',exact=True).click()
 assert not errors,errors
 browser.close()
print('Focused product selection, templates, count resume, spirits, archives, receiving and mobile widths passed.')
