from pathlib import Path
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1]
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':390,'height':844});errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:4173/',wait_until='networkidle')
 page.get_by_role('button',name='Count & edit stock',exact=True).click()
 dialog=page.get_by_role('dialog',name='Stock editor')
 expect(dialog).to_be_visible()
 dialog.get_by_role('button',name='Add product',exact=True).first.click()
 dialog.get_by_label('Start from').select_option('briskaCan')
 dialog.get_by_label('Product name',exact=True).fill('Briska Mango test')
 dialog.get_by_label('Flavour / brand').fill('Mango')
 dialog.get_by_label('Storage location',exact=True).fill('Test shelf')
 expect(dialog.get_by_label('Units per pack / crate')).to_have_value('24')
 dialog.get_by_role('button',name='Save product',exact=True).click()
 expect(dialog.get_by_text('Briska Mango test',exact=True)).to_be_visible()
 dialog.locator('#inv-location').select_option('Test shelf')
 dialog.get_by_role('button',name='Count this location',exact=True).click()
 dialog.get_by_role('button',name='Increase Full packs').click()
 dialog.get_by_label('Loose units',exact=True).fill('12')
 dialog.get_by_label('Loose units',exact=True).blur()
 expect(dialog.locator('.count-total')).to_have_text('36 cans')
 expect(dialog.locator('#draft-status')).to_contain_text('Preview draft')
 dialog.get_by_role('button',name='Close',exact=True).click()
 page.get_by_role('button',name='Count & edit stock',exact=True).click()
 dialog.get_by_role('button',name='Resume count',exact=True).first.click()
 expect(dialog.locator('.count-total')).to_have_text('36 cans')
 expect(dialog.get_by_text('Not yet confirmed',exact=True)).to_be_visible()
 dialog.get_by_role('button',name='Confirm & next',exact=True).click()
 expect(dialog.get_by_role('heading',name='Review count')).to_be_visible()
 dialog.get_by_role('button',name='Publish count',exact=True).click()
 expect(dialog.locator('#draft-status')).to_have_text('Preview count applied')
 # Create a spirit bottle and use a fraction button rather than typing quantities.
 dialog.get_by_role('button',name='Add product',exact=True).first.click()
 dialog.get_by_label('Start from').select_option('spirit')
 dialog.get_by_label('Product name',exact=True).fill('House gin 70 cl')
 dialog.get_by_label('Storage location',exact=True).fill('Spirits test')
 dialog.get_by_role('button',name='Save product',exact=True).click()
 dialog.locator('#inv-location').select_option('Spirits test')
 dialog.get_by_role('button',name='Count this location',exact=True).click()
 dialog.get_by_role('button',name='Increase Full bottles').click()
 dialog.get_by_role('button',name='+ Opened bottle',exact=True).click()
 dialog.get_by_role('button',name='¼',exact=True).click()
 expect(dialog.locator('.count-total')).to_contain_text('875 ml')
 assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
 dock=dialog.locator('.count-dock').bounding_box();assert dock['y']+dock['height']<=845
 page.screenshot(path=str(ROOT/'test-results/inventory-mobile.png'))
 dialog.get_by_role('button',name='Confirm & next',exact=True).click()
 dialog.get_by_role('button',name='Publish count',exact=True).click()
 dialog.get_by_role('button',name='Edit',exact=True).click()
 dialog.get_by_role('button',name='Archive product',exact=True).click()
 expect(dialog.get_by_text('House gin 70 cl',exact=True)).not_to_be_visible()
 dialog.get_by_role('button',name='Show archived',exact=True).click()
 dialog.get_by_role('button',name='Edit',exact=True).click()
 dialog.get_by_role('button',name='Restore product',exact=True).click()
 dialog.get_by_role('button',name='Show active products',exact=True).click()
 expect(dialog.get_by_text('House gin 70 cl',exact=True)).to_be_visible()
 dialog.get_by_role('button',name='Close',exact=True).click()
 assert not errors,errors
 browser.close()
print('Phone counting passed: product templates, draft resume, explicit confirmation, pack conversion, spirit fractions, archive/restore and thumb dock.')
